name: Linux-Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for proper versioning with setuptools-scm

      # Configure python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Install dependcies
      - name: Install dependencies (no dependencies required for the tool !)
        run: |
          python -m pip install pyinstaller setuptools-scm

      # Get commit ID to get a version number
      - name: Get App Version
        id: get_version
        run: |
          echo "APP_VERSION=$(python -c 'from setuptools_scm import get_version; print(get_version())')" >> $GITHUB_OUTPUT

      # Build the app
      - name: Build tcreator-open
        run: |
          pyinstaller --clean -y -n "tcreator-open-x86_64-linux" --onefile src/tcreator-open.py
      - name: Build tcreator-write
        run: |
          pyinstaller --clean -y -n "tcreator-write-x86_64-linux" --onefile src/tcreator-write.py
      - name: Build tcreator-gui
        run: |
          pyinstaller --clean -y -n "tcreator-x86_64-linux" --add-data="src/gui/logo_128.png:gui/." --onefile src/tcreator-gui.py

      # Upload executables
      - name: Upload executable file to repo (write)
        uses: actions/upload-artifact@v4
        with:
          name: tcreator-write-x86_64-linux
          path: dist/tcreator-write-x86_64-linux

      - name: Upload executable file to repo (open)
        uses: actions/upload-artifact@v4
        with:
          name: treator-open-x86_64-linux
          path: dist/tcreator-open-x86_64-linux

      - name: Upload executable file to repo (gui)
        uses: actions/upload-artifact@v4
        with:
          name: treator-x86_64-linux
          path: dist/tcreator-x86_64-linux
