name: Build and Release with PyInstaller (Linux)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for proper versioning with setuptools-scm

      # Multiples runs for different python versions.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (no dependencies required for the tool !)
        run: |
          python -m pip install pyinstaller setuptools-scm

      - name: Get App Version
        id: get_version
        run: |
          echo "APP_VERSION=$(python -c 'from setuptools_scm import get_version; print(get_version())')" >> $GITHUB_OUTPUT

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean -y -n "template-creator-x86_64_windows-${{ steps.get_version.outputs.APP_VERSION }}.exe" --onefile --add-data="src/config:config" --icon="icons/icon.ico" src/main.py

      - name: Create .tar.gz
        run: |
          Compress-Archive src template-creator-x86_64-windows-${{ steps.get_version.outputs.APP_VERSION }}.zip
          echo "template-creator-x86_64-windows-${{ steps.get_version.outputs.APP_VERSION }}.zip" >> $GITHUB_ENV
          echo "template-creator-x86_64-windows-${{ steps.get_version.outputs.APP_VERSION }}.zip" >> $GITHUB_ENV
