name: Release Application

on:
  push:
    branches:
      - main

jobs:
  # Run the Linux build
  job1:
    uses: lheywang/TemplateCreator/.github/workflows/python-linux.yaml@main

  # Run the Windows build
  job2:
    uses: lheywang/TemplateCreator/.github/workflows/python-windows.yaml@main

  # Run the MacOS build
  job3:
    uses: lheywang/TemplateCreator/.github/workflows/python-mac.yaml@main

  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]

    steps:
      # Checkout git
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create an artifact folder
        run: |
          mkdir -p artifacts
          mkdir -p artifacts/Windows
          mkdir -p artifacts/Linux
          mkdir -p artifacts/MacOS

      # Download all artifacts
      - name: Download Artifacts (all)
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      # Create a release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.workflow_run.head_commit.message }}"
          name: "Your Application v${{ github.event.workflow_run.head_commit.message }}"
          body: |
            Application release, contain all executables for :
              - Linux x86_64
              - Windows x86_64
              - MacOS aarch64

            As well as zip files for the different platforms (require a bare python installation).
          files: |
            artifacts/*
